#!/bin/sh

set -e

MAKE_JOBS="$1"
COMMIT="$2"
ARCH="$(uname -m)"

cd /deps
git clone https://github.com/zig-lang/zig --depth=1
cd /deps/zig
git checkout "$COMMIT"
mkdir -p /deps/zig/build
cd /deps/zig/build
cmake .. -DZIG_STATIC=on -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH=/deps/local -DCMAKE_INSTALL_PREFIX=/deps/install
make "$MAKE_JOBS" install
./zig build docs
mv ../zig-cache/langref.html /deps/install/
mv ../LICENSE /deps/install/

cd /deps
mv install/bin/zig install/
rmdir install/bin
VERSION="$(install/zig version)"
DIRNAME="zig-linux-$ARCH-$VERSION"
mv install "$DIRNAME"
tar cfJ "$DIRNAME.tar.xz" "$DIRNAME"
mv "$DIRNAME.tar.xz" /z/
